# Generated by Django 4.1.3 on 2024-04-03 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_department_name', models.CharField(max_length=100)),
                ('app_doctorr_name', models.CharField(max_length=100)),
                ('app_date', models.DateField()),
                ('app_time', models.CharField(max_length=50)),
                ('full_name', models.CharField(max_length=100)),
                ('mobile_num', models.BigIntegerField()),
                ('message', models.TextField()),
            ],
        ),
    ]
