# Generated by Django 5.0.2 on 2024-04-04 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_appointmentdetail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointmentdetail',
            old_name='app_doctorr_name',
            new_name='app_doctor_name',
        ),
    ]
